version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    volumes:
      - nest-app-node-modules:/usr/src/app/node_modules
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - app-network
    command: pnpm run start:dev
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3001
      - NEXT_TELEMETRY_DISABLED=1
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=dockdock

  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dockdock
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  nest-app-node-modules:
